tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_mess_detector: true
    php_changetracking: true
    external_code_coverage:
        timeout: 600
    php_code_sniffer: true
    php_cs_fixer:
        config: { level: all }
    sensiolabs_security_checker: true
    external_code_coverage: true

filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*]

checks:
    php:
        unused_parameters: true
        verify_property_names: true
        verify_argument_usable_as_reference: true
        verify_access_scope_valid: true
        variable_existence: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        unused_variables: true
        unused_properties: true
        unused_methods: true
        unreachable_code: true
        too_many_arguments: true
        symfony_request_injection: true
        switch_fallthrough_commented: true
        sql_injection_vulnerabilities: true
        spacing_of_function_arguments: true
        spacing_around_non_conditional_operators: true
        spacing_around_conditional_operators: true
        avoid_closing_tag: true
        avoid_aliased_php_functions: true
        assignment_of_null_return: true
        argument_type_checks: true
        align_assignments: true
        avoid_conflicting_incrementers: true
        avoid_corrupting_byteorder_marks: true
        avoid_duplicate_types: true
        avoid_entity_manager_injection: true
        avoid_fixme_comments: true
        avoid_length_functions_in_loops: true
        avoid_multiple_statements_on_same_line: true
        avoid_perl_style_comments: true
        avoid_superglobals: true
        avoid_tab_indentation: true
        avoid_todo_comments: true
        avoid_unnecessary_concatenation: true
        avoid_usage_of_logical_operators: true
        avoid_useless_overridden_methods: true
        blank_line_after_namespace_declaration: true
        catch_class_exists: true
        classes_in_camel_caps: true
        closure_use_modifiable: true
        closure_use_not_conflicting: true
        code_rating: true
        deadlock_detection_in_loops: true
        deprecated_code_usage: true
        duplication: true
        encourage_shallow_comparison: true
        encourage_postdec_operator: true
        encourage_single_quotes: true
        ensure_lower_case_builtin_functions: true
        fix_doc_comments: true
        fix_identation_4spaces: true
        fix_php_opening_tag: true
        fix_line_ending: true
        foreach_traversable: true
        useless_calls: true
        use_statement_alias_conflict: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        space_after_cast: true
        single_namespace_per_use: true
        simplify_boolean_return: true
        return_doc_comments: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_php_tag_first: true
        remove_trailing_whitespace: true
        psr2_switch_declaration: true
        psr2_control_structure_declaration: true
        psr2_class_declaration: true
        property_assignments: true
        properties_in_camelcaps: true
        phpunit_assertions: true
        php5_style_constructor: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        overriding_private_members: true
        one_class_per_file: true
        non_commented_empty_catch_block: true
        no_unnecessary_if: true
        no_unnecessary_final_modifier: true
        no_underscore_prefix_in_methods: true
        no_unnecessary_function_call_in_for_loop: true
        no_trait_type_hints: true
        no_underscore_prefix_in_properties: true
        no_trailing_whitespace: true
        no_space_before_semicolon: true
        no_space_around_object_operator: true
        no_short_open_tag: true
        no_short_method_names:
            minimum: '3'
        no_mixed_inline_html: true
        no_long_variable_names:
            maximum: '30'
        no_goto: true
        no_global_keyword: true
        no_exit: true
        no_eval: true
        no_error_suppression: true
        no_else_if_statements: true
        no_debug_code: true
        missing_arguments: true
        lowercase_php_keywords: true
        lowercase_basic_constants: true
        instanceof_class_exists: true
        function_in_camel_caps: true
        function_body_start_on_same_line: true